ERROR conda.cli.main_run:execute(32): Subprocess for 'conda run ['python', '../train_supervised.py', '--trial', 'pretrain', '--model_path', './saved_model', '--tb_path', './mytensorboard', '--data_root', '/home/dhruv.gupta.cse17.iitbhu/datasets', '--dataset', 'FC100']' command failed.  (See above for error)
which: no fi_info in (/home/apps/bio_tools/conda/bin:/home/apps/cuda-11.1/bin:/home/apps/bio_tools/conda/condabin:/usr/lib64/qt-3.3/bin:/home/dhruv.gupta.cse17.iitbhu/perl5/bin:/opt/ohpc/pub/utils/prun/1.3:/opt/ohpc/pub/utils/autotools/bin:/opt/ohpc/pub/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/ibutils/bin:/home/dhruv.gupta.cse17.iitbhu/.local/bin:/home/dhruv.gupta.cse17.iitbhu/bin)
/home/dhruv.gupta.cse17.iitbhu/.conda/envs/rfs_latest_packages/lib/python3.9/site-packages/torch/utils/data/dataloader.py:478: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 1, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
/home/dhruv.gupta.cse17.iitbhu/.conda/envs/rfs_latest_packages/lib/python3.9/site-packages/torch/utils/data/dataloader.py:478: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 1, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
Traceback (most recent call last):
  File "/home/dhruv.gupta.cse17.iitbhu/rfs/scripts/../train_supervised.py", line 341, in <module>
    main()
  File "/home/dhruv.gupta.cse17.iitbhu/rfs/scripts/../train_supervised.py", line 250, in main
    train_acc, train_loss = train(epoch, train_loader, model, criterion, optimizer, opt)
  File "/home/dhruv.gupta.cse17.iitbhu/rfs/scripts/../train_supervised.py", line 305, in train
    acc1, acc5 = accuracy(output, target, topk=(1, 5))
  File "/home/dhruv.gupta.cse17.iitbhu/rfs/util.py", line 82, in accuracy
    correct_k = correct[:k].view(-1).float().sum(0, keepdim=True)
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

